### ISSUE TITLE
Could not locate executable ifort / ifc ?

### ISSUE THREAD

**Issue by eudoxos** [bpartridge/PyPhi#3]
Great script, appreciated a lot. I have Parallel Studio XE 2015 installed (which allegedly does support fortran), but it does not seem to contain `ifort` or `ifc` (`icc` is there, and is in `$PATH` by sourcing the scripts), though I installed all the components. What is the problem? Thanks for hints.

The build halts with the following:

```
[....]
creating build/lib.linux-x86_64-2.7/scipy/_build_utils
copying scipy/_build_utils/__init__.py -> build/lib.linux-x86_64-2.7/scipy/_build_utils
copying scipy/_build_utils/_fortran.py -> build/lib.linux-x86_64-2.7/scipy/_build_utils
running build_clib
customize IntelMICCompiler
customize IntelMICCompiler using build_clib
customize IntelMICFCompiler
Could not locate executable ifort
Could not locate executable ifc
Traceback (most recent call last):
  File "numpyxc.py", line 73, in <module>
    setup.setup_package()
  File "/home/eudoxos/build/PyPhi/scipy/setup.py", line 227, in setup_package
    setup(**metadata)
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/command/install.py", line 57, in run
    r = old_install.run(self)
  File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
    self.run_command('build')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/command/build.py", line 39, in run
    old_build.run(self)
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/command/build_clib.py", line 92, in run
    self._f_compiler.customize(self.distribution)
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/fcompiler/__init__.py", line 464, in customize
    self.find_executables()
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/fcompiler/__init__.py", line 354, in find_executables
    raise CompilerNotFound('%s: f90 nor f77' % ctype)
numpy.distutils.fcompiler.CompilerNotFound: intelmic: f90 nor f77
```

**Comment by eudoxos** [comment]
Alright, so this was just my issue of not selecting the right things to install with XE studio. Sorry for the noise.
